config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  resources :shopping_carts, only:[:index]
  resources :items, only:[:index, :show]
  resource :shopping_cart, only: [:show, :update, :create, :destroy] do
    get 'order'
    resources :items, only: [:add, :remove], controller: 'shopping_carts' do
      get 'add'
      get 'remove'
    end
  end
  resource :user, only: [:show, :update] do
    resource :delivery_info, only:[:new, :edit, :create, :update] do
      resource :order, only:[:create]
    end
    resources :orders, only:[:index, :show, :create]
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def tax_pct
    8.0
  end

  def shipping_charge
    settlement_charge.to_i + packing_charge.to_i
  end

  def total_taxes
    (subtotal.to_i + shipping_charge.to_i) * tax_pct.to_i / 100
  end

  def total_price
    subtotal.to_i + shipping_charge.to_i + total_taxes.to_i
  end

  private
    def settlement_charge
      if subtotal.to_i < 10000
        300
      elsif subtotal.to_i < 30000
        400
      elsif subtotal.to_i < 100000
        600
      else
        1000
      end
    end

    def packing_charge
      (total_unique_items / 5.to_f).ceil * 600
    end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!, only:[:order]
  before_action :extract_shopping_cart
  before_action :get_item, only:[:add, :create, :remove]
  before_action :add_item, only:[:add, :create]

  def index
  end

  def add
  end

  def remove
    @shopping_cart.remove(@item, 1)
    redirect_to shopping_carts_path
  end

  def create
    redirect_to shopping_carts_path
  end

  def order
    @order = Order.new
    @delivery_info = current_user.delivery_info
  end

  def destroy
    @shopping_cart.clear
    redirect_to shopping_carts_path
  end

  private
  def extract_shopping_cart
    shopping_cart_id = session[:shopping_cart_id]
    @shopping_cart = session[:shopping_cart_id] ? ShoppingCart.find(shopping_cart_id) : ShoppingCart.create
    session[:shopping_cart_id] = @shopping_cart.id
  end

  def get_item
    @item = Item.find(params[:item_id])
  end

  def add_item
    @shopping_cart.add(@item, @item.price)
  end
end

app/views/shopping_carts/_shopping_cart_item.html.haml
%tr
  %td
    = shopping_cart_item.item.name
  %td
    = number_to_currency shopping_cart_item.item.price
  %td
    = shopping_cart_item.quantity
  %td
    = link_to 'カートから削除', shopping_cart_item_remove_path(shopping_cart_item.item), { class: 'btn btn-default', data: { confirm: '商品を削除しますか?' } }

app/views/shopping_carts/add.js.erb
alert("商品をカートに追加しました");

app/views/shopping_carts/index.html.haml
%h4 ショッピングカート

%p#notice= notice

%table.table.table-hover
  %thead
    %tr
      %th 商品
      %th 価格
      %th 数量
      %th 
  %tbody
    = render :partial => 'shopping_cart_item', :collection => @shopping_cart.shopping_cart_items

%b 合計:
= number_to_currency @shopping_cart.subtotal
%b 消費税:
= number_to_currency @shopping_cart.taxes
%b 総額:
= number_to_currency @shopping_cart.total

%br
%br
- if @shopping_cart.shopping_cart_items.size > 0
  = link_to '注文する', order_shopping_cart_path, { class: 'btn btn-default' }
  = link_to 'カートをクリア', @shopping_cart, { class: 'btn btn-default', method: :delete, data: { confirm: '全ての商品を削除しますか?' }}

app/views/shopping_carts/order.html.haml
%h4 商品注文

%h5 注文一覧
%table.table
  %thead
    %tr
      %th 商品
      %th 価格
      %th 数量
  %tbody
    - @shopping_cart.shopping_cart_items.each do |shopping_cart_item|
      %tr
        %td= shopping_cart_item.item.name
        %td= shopping_cart_item.item.price
        %td= shopping_cart_item.quantity
%br
%br
%b 合計:
= number_to_currency @shopping_cart.subtotal
%br
%b 配送手数料:
= number_to_currency @shopping_cart.shipping_charge
%br
%b 消費税:
= number_to_currency @shopping_cart.total_taxes
%br
%b 総額:
= number_to_currency @shopping_cart.total_price
%br

%h5 配送先

- if @delivery_info != nil
  %table.table
    %thead
      %tr
        %th 配送先名
        %th 配送先住所
    %tbody
      %tr
        %td
          = @delivery_info.name
        %td
          = @delivery_info.address

  %h5 配送日時
  = bootstrap_form_for @order, url: user_delivery_info_order_path do |f|
    = f.select :delivery_date, Order.delivery_dates
    = f.select :time_range_id, Order.localed_time_ranges, {}, class: 'form-control'
    = f.hidden_field :delivery_info_id, value: @delivery_info.id
    = f.hidden_field :settlement_charge, value: @shopping_cart.subtotal
    = f.hidden_field :delivery_charge, value:@shopping_cart.shipping_charge
    .actions
      = f.submit '注文確定'

- else
  = link_to '配送先情報追加', new_user_delivery_info_path(current_user), { class: 'btn btn-default' }