config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  resources :shopping_carts, only:[:index]
  resources :items, only:[:index, :show]
  resource :shopping_cart, only: [:show, :update, :create, :destroy] do
    get 'order'
    resources :items, only: [:add, :remove], controller: 'shopping_carts' do
      get 'add'
      get 'remove'
    end
  end
  resource :user, only: [:show, :update] do
    resource :delivery_info, only:[:new, :edit, :create, :update] do
      resource :order, only:[:create]
    end
    resources :orders, only:[:index, :show, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :delivery_info
  has_many :order
  enum role: { admin: 1, member: 2 }
  validates :nickname, length: { maximum: 120 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update]

  def show
    @delivery_info = current_user.delivery_info
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました.' }
      else
        @delivery_info = current_user.delivery_info
        format.html { render :show, notice: 'ユーザー情報の更新に失敗しました' }
      end
    end
  end

private
    def set_user
      @user = User.find_or_create_by(id: current_user.id)
    end

    def user_params
      params.require(:user).permit(:nickname)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= bootstrap_form_for @user, format: :html do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user_info from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.text_field :nickname
  .actions
    = f.submit '保存'

app/views/users/show.html.haml
%h4 ユーザー情報
%p#notice= notice

= render 'form'

%br
- if @delivery_info == nil
  = link_to '配送先情報追加', new_user_delivery_info_path(current_user), { class: 'btn btn-default' }
- else
  %h4 配送先情報
  %table.table.table-condensed
    %thead
      %tr
        %th 配送先宛名
        %th 配送先住所
        %th{:width => "50"}
        %th{:width => "50"}

    %tbody
      %tr
        %td= @delivery_info.name
        %td= @delivery_info.address
        %td= link_to '編集', edit_user_delivery_info_path(@delivery_info), class: 'btn btn-default'

  = link_to '購入履歴を見る', user_orders_path, { class: 'btn btn-default' }