config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  resources :shopping_carts, only:[:index]
  resources :items, only:[:index, :show]
  resource :shopping_cart, only: [:show, :update, :create, :destroy] do
    get 'order'
    resources :items, only: [:add, :remove], controller: 'shopping_carts' do
      get 'add'
      get 'remove'
    end
  end
  resource :user, only: [:show, :update] do
    resource :delivery_info, only:[:new, :edit, :create, :update] do
      resource :order, only:[:create]
    end
    resources :orders, only:[:index, :show, :create]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  require 'holiday_japan'

  belongs_to :user
  has_many :order_items
  enum time_range_id: { free: 0, am: 1, pm1: 2, pm2: 3, pm4: 4, pm5: 5 }

  def self.delivery_dates
    dates = Hash.new
    today = Date.current
    elapsed_date = 3
    until dates.size == 12
      unless holiday?(today.since(elapsed_date.days))
        dates.store(today.since(elapsed_date.days).strftime("%Y年 %m月 %d日"), today.since(elapsed_date.days))
      end
      elapsed_date += 1
    end
    dates
  end

  def self.localed_time_ranges
    time_range_ids.keys.map do |k|
      [ApplicationController.helpers.t("enums.order.time_range_id.#{k}"), k]
    end
  end

  private
  def self.holiday?(date)
    if !HolidayJapan.check(date)
      if date.saturday? || date.sunday?
        return true
      end
      return false
    end
    return true
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.order.all
  end

  def show
    @order_items = OrderItem.where(order_id: params[:id])
  end

  def create
    @order = Order.new(order_params.merge(order_date: Time.current))
    order_items.each do |order_item|
        @order.order_items.new(item_id: order_item.item.id, quantity: order_item.quantity)
    end
    respond_to do |format|
      if @order.save
        ShoppingCart.find(cart_id).clear
        format.html { render :complete, notice: '商品注文が確定しました.' }
      else
        format.html { redirect_to shopping_carts_path, notice: '商品注文に失敗しました.' }
       end
    end
  end

  private
    def order_params
      params.require(:order).permit(:user_id, :order_date, :delivery_info_id, :delivery_date, :time_range_id, :settlement_charge, :delivery_charge).merge(user_id: current_user.id)
    end

    def cart_id
      session[:shopping_cart_id]
    end

    def order_items
      ShoppingCart.find(cart_id).shopping_cart_items
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :order_date
    = f.datetime_select :order_date
  .field
    = f.label :delivery_info_id
    = f.number_field :delivery_info_id
  .field
    = f.label :delivery_date
    = f.date_select :delivery_date
  .field
    = f.label :time_range_id
    = f.number_field :time_range_id
  .field
    = f.label :settelment_charge
    = f.number_field :settelment_charge
  .field
    = f.label :delivery_charge
    = f.number_field :delivery_charge
  .actions
    = f.submit 'Save'

app/views/orders/complete.html.haml
%h4 注文完了
%p#notice= notice

%p ご注文ありがとうございました。

= link_to 'お買い物に戻る', items_path, { class: 'btn btn-default' }

app/views/orders/index.html.haml
%h4 注文履歴

%table.table.table-hover
  %thead
    %tr
      %th 注文日
      %th 配送日
      %th 配送時間
      %th 小計
      %th 配送料
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.order_date.strftime("%Y年%m月%d日 %H:%M:%S") 
        %td= order.delivery_date.strftime("%Y年%m月%d日") 
        %td= order.time_range_id_i18n
        %td= number_to_currency order.settlement_charge
        %td= number_to_currency order.delivery_charge
        %td= link_to '注文詳細', user_order_path(order), { class: 'btn btn-default' }
%br

= link_to '戻る', current_user, { class: 'btn btn-default' }

app/views/orders/show.html.haml
%h4 注文詳細

%table.table
  %thead
    %tr
      %th 商品名
      %th 注文数

  %tbody
    - @order_items.each do |order_item|
      %tr
        %td= order_item.item.name
        %td= order_item.quantity
%br

= link_to '戻る', user_orders_path, { class: 'btn btn-default' }