config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'items#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  resources :shopping_carts, only:[:index]
  resources :items, only:[:index, :show]
  resource :shopping_cart, only: [:show, :update, :create, :destroy] do
    get 'order'
    resources :items, only: [:add, :remove], controller: 'shopping_carts' do
      get 'add'
      get 'remove'
    end
  end
  resource :user, only: [:show, :update] do
    resource :delivery_info, only:[:new, :edit, :create, :update] do
      resource :order, only:[:create]
    end
    resources :orders, only:[:index, :show, :create]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.haml
%center
  %span sakura-market

app/views/application/_header.html.haml
.container-fluid
  .row
    .col-md-3.vbottom
      %h3 さくらマーケット
    .col-md-5.vbottom
      .container-fluid
        .row
          .col-md-4.center-block.align-middle= link_to '日記を見る', root_path
          .col-md-4= link_to 'お買い物', items_path
          .col-md-4= link_to 'ショッピングカート', shopping_carts_path
    .col-md-3.vbottom.text-right
      -if user_signed_in?
        .container-fluid
          .row
            .col-md-6= link_to 'ユーザー情報', current_user, { class: 'btn btn-default' } 
            .col-md-6= link_to 'ログアウト', destroy_user_session_path, { class: 'btn btn-default' } 

      -else
        =link_to 'ログイン', user_session_path, { class: 'btn btn-default' } 